// Code generated by go-swagger; DO NOT EDIT.

// Package restapi Onmi
//
//	Onmi Batch
//	Schemes:
//	  http
//	  https
//	Host: 0.0.0.0:8080
//	BasePath: /
//	Version: 0.0.1
//
//	Consumes:
//	  - application/json
//
//	Produces:
//	  - application/json
//
// swagger:meta
package restapi
