// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http",
    "https"
  ],
  "swagger": "2.0",
  "info": {
    "description": "Onmi Batch",
    "title": "Onmi",
    "version": "0.0.1"
  },
  "host": "0.0.0.0:8080",
  "basePath": "/",
  "paths": {
    "/healthCheck": {
      "get": {
        "security": [
          {}
        ],
        "description": "Check server availability",
        "tags": [
          "Standard"
        ],
        "summary": "health-check",
        "operationId": "health-check",
        "responses": {
          "200": {
            "description": "ok",
            "schema": {
              "type": "object",
              "properties": {
                "ok": {
                  "type": "boolean"
                }
              }
            }
          },
          "500": {
            "description": "pkg server error",
            "schema": {
              "$ref": "#/definitions/internalServerError"
            }
          }
        }
      }
    },
    "/process/items": {
      "post": {
        "description": "Processing items via external service",
        "tags": [
          "Process"
        ],
        "summary": "process_items",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "type": "object",
              "required": [
                "items"
              ],
              "properties": {
                "items": {
                  "description": "items for processing",
                  "type": "array",
                  "items": {
                    "$ref": "#/definitions/item"
                  }
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "ok",
            "schema": {
              "type": "object",
              "properties": {
                "ok": {
                  "type": "boolean"
                }
              }
            }
          },
          "500": {
            "description": "internal server error",
            "schema": {
              "$ref": "#/definitions/internalServerError"
            }
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "error": {
      "type": "object",
      "required": [
        "code",
        "message"
      ],
      "properties": {
        "code": {
          "description": "either same as HTTP Status Code OR \u003e= 600.",
          "type": "integer",
          "format": "int32"
        },
        "message": {
          "type": "string"
        }
      }
    },
    "internalServerError": {
      "type": "string"
    },
    "item": {
      "type": "object",
      "required": [
        "title",
        "key"
      ],
      "properties": {
        "key": {
          "description": "key of item",
          "type": "string",
          "example": "some_key"
        },
        "title": {
          "description": "title of item",
          "type": "string",
          "example": "Some title"
        }
      }
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http",
    "https"
  ],
  "swagger": "2.0",
  "info": {
    "description": "Onmi Batch",
    "title": "Onmi",
    "version": "0.0.1"
  },
  "host": "0.0.0.0:8080",
  "basePath": "/",
  "paths": {
    "/healthCheck": {
      "get": {
        "security": [
          {}
        ],
        "description": "Check server availability",
        "tags": [
          "Standard"
        ],
        "summary": "health-check",
        "operationId": "health-check",
        "responses": {
          "200": {
            "description": "ok",
            "schema": {
              "type": "object",
              "properties": {
                "ok": {
                  "type": "boolean"
                }
              }
            }
          },
          "500": {
            "description": "pkg server error",
            "schema": {
              "$ref": "#/definitions/internalServerError"
            }
          }
        }
      }
    },
    "/process/items": {
      "post": {
        "description": "Processing items via external service",
        "tags": [
          "Process"
        ],
        "summary": "process_items",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "type": "object",
              "required": [
                "items"
              ],
              "properties": {
                "items": {
                  "description": "items for processing",
                  "type": "array",
                  "items": {
                    "$ref": "#/definitions/item"
                  }
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "ok",
            "schema": {
              "type": "object",
              "properties": {
                "ok": {
                  "type": "boolean"
                }
              }
            }
          },
          "500": {
            "description": "internal server error",
            "schema": {
              "$ref": "#/definitions/internalServerError"
            }
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "error": {
      "type": "object",
      "required": [
        "code",
        "message"
      ],
      "properties": {
        "code": {
          "description": "either same as HTTP Status Code OR \u003e= 600.",
          "type": "integer",
          "format": "int32"
        },
        "message": {
          "type": "string"
        }
      }
    },
    "internalServerError": {
      "type": "string"
    },
    "item": {
      "type": "object",
      "required": [
        "title",
        "key"
      ],
      "properties": {
        "key": {
          "description": "key of item",
          "type": "string",
          "example": "some_key"
        },
        "title": {
          "description": "title of item",
          "type": "string",
          "example": "Some title"
        }
      }
    }
  }
}`))
}
